#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-xopen
Version  : 1.0.0
Release  : 8
URL      : https://cran.r-project.org/src/contrib/xopen_1.0.0.tar.gz
Source0  : https://cran.r-project.org/src/contrib/xopen_1.0.0.tar.gz
Summary  : Open System Files, 'URLs', Anything
Group    : Development/Tools
License  : MIT
BuildRequires : R-cli
BuildRequires : R-processx
BuildRequires : R-ps
BuildRequires : R-rlang
BuildRequires : R-withr
BuildRequires : buildreq-R

%description
# xopen
> Open System Files, URLs, Anything
[![Linux Build Status](https://travis-ci.org/r-lib/xopen.svg?branch=master)](https://travis-ci.org/r-lib/xopen)
[![Windows Build status](https://ci.appveyor.com/api/projects/status/github/r-lib/xopen?branch=master&svg=true)](https://ci.appveyor.com/project/gaborcsardi/xopen)
[![](http://www.r-pkg.org/badges/version/xopen)](http://www.r-pkg.org/pkg/xopen)
[![CRAN RStudio mirror downloads](http://cranlogs.r-pkg.org/badges/xopen)](http://www.r-pkg.org/pkg/xopen)

%prep
%setup -q -c -n xopen

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1552916389

%install
export SOURCE_DATE_EPOCH=1552916389
rm -rf %{buildroot}
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library xopen
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library xopen
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library xopen
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc  xopen || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/xopen/DESCRIPTION
/usr/lib64/R/library/xopen/INDEX
/usr/lib64/R/library/xopen/LICENSE
/usr/lib64/R/library/xopen/Meta/Rd.rds
/usr/lib64/R/library/xopen/Meta/features.rds
/usr/lib64/R/library/xopen/Meta/hsearch.rds
/usr/lib64/R/library/xopen/Meta/links.rds
/usr/lib64/R/library/xopen/Meta/nsInfo.rds
/usr/lib64/R/library/xopen/Meta/package.rds
/usr/lib64/R/library/xopen/NAMESPACE
/usr/lib64/R/library/xopen/NEWS.md
/usr/lib64/R/library/xopen/R/xopen
/usr/lib64/R/library/xopen/R/xopen.rdb
/usr/lib64/R/library/xopen/R/xopen.rdx
/usr/lib64/R/library/xopen/help/AnIndex
/usr/lib64/R/library/xopen/help/aliases.rds
/usr/lib64/R/library/xopen/help/paths.rds
/usr/lib64/R/library/xopen/help/xopen.rdb
/usr/lib64/R/library/xopen/help/xopen.rdx
/usr/lib64/R/library/xopen/html/00Index.html
/usr/lib64/R/library/xopen/html/R.css
/usr/lib64/R/library/xopen/tests/testthat.R
/usr/lib64/R/library/xopen/tests/testthat/helper.R
/usr/lib64/R/library/xopen/tests/testthat/test.R
/usr/lib64/R/library/xopen/xdg-open
